version : "3"
services:
    yolo_app:
        image: jamescrosbie/object_detection:latest
        ports:
            # local host : docker host
            - "8888:8888"

        volumes:
            # local file location : container location
            - ./samples:/scripts/samples
